### ISSUE TITLE
error: couldn't connect to server: unknown (code -1)

### ISSUE THREAD

**Issue by mbootsman** [richardjoo/HTMLCOIN#3]
I have the wallet complied (2.0.0.3) and built on Ubuntu. The qt client is running, and it is connected to peers.
When I execute `src/htmlcoin-cli getinfo` I get this error: 
`error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
`

What am I doing wrong?

**Comment by richardjoo** [comment]
that is because your blockchain is not fully synchronized.  please check your connection and also check your blockchain size

`src/htmlcoin-cli getinfo` to compare the block

Also, Peter posted on his github that v.2.0.0.3 has a bug in connection and he will fix this issue.
please check this note on FAQ page

https://github.com/richardjoo/HTMLCOIN/tree/master/FAQ

there is an instruction to add more nodes to your wallet.

**Comment by richardjoo** [comment]
also please make sure your server is running
did you run the command before?

`src/htamlcoind --daemon`

**Comment by mbootsman** [comment]
the `--daemon` did the trick. Now the wallet is running on the background. Thanks.

**Comment by Deeprai32037i** [comment]
Someone hacked my all social media account and my And my home Internet IP address and my iCloud’s IP address my device I am in and the IP address creator helping people there’s a helping websites on the Wikipedia so whatever’s third-party websites using after my use all data so please help mepersonal information or personal data on my all Gmail account Samsung account Google Drive data Apple iCloud iPhone you are number all other social media all account and my domain name my service Canada account my face ID everything scammer you can help me my banking information my credit debit all other information so I want to hug you can help me put it to me pleaseAll my URL number on my domain name of my all service Canada account my all social media accounts without my permission my tax regarding all information you can help me protect me
