### ISSUE TITLE
Error with trying to run htmlcoin-cli-mining-multiple.sh

### ISSUE THREAD

**Issue by tommaton** [richardjoo/HTMLCOIN#9]
I'm trying to run the multi mining on my Raspberry Pi 3, each time I run the command
```
sudo ./htmlcoin-cli-mining-multiple.sh
```
I get the following error
```
./htmlcoin-cli-mining-multiple.sh: 33: ./htmlcoin-cli-mining-multiple.sh: 0: not found
```

The single mining works no problem and help in solving this would be great.

**Comment by zatmar** [comment]
Add this to the first line of the file:
``#!/bin/bash``

**Comment by tommaton** [comment]
@zatmar I've just added that, I'm getting a slightly different error now (just second path is missing from the message).
```
./htmlcoin-cli-mining-multiple.sh: 34: 0: not found
```

**Comment by zatmar** [comment]
Change this line:
`miner_max=`
for this
`miner_max=3`
With this you establish the miners maximum.

**Comment by tommaton** [comment]
Afraid still the same error message.

**Comment by richardjoo** [comment]
this code was done by other contributor and I did not touch the code since a different user worked on better version.  If you are interested in using multiple session, I recommend you to check out cl04ker's github :-)

https://github.com/cl04ker/HTMLCOIN-Scripts

sorry I did not work on this code though...
